### ISSUE TITLE
NPM Package page refers to incorrect repository

### ISSUE THREAD

**Issue by ThomasRedstone** [dalisoft/npm-packages#190]
## Bug Report

**Is you sponsoring this project**

**No**

**Type package name**

@dalisoft/jwt

**Current Behavior**
https://www.npmjs.com/package/@dalisoft/jwt refers to https://github.com/dalisoft/jwt which is now out of date.

**Expected behavior/code**
https://www.npmjs.com/package/@dalisoft/jwt should refer to https://github.com/dalisoft/npm-packages/tree/master/packages/jwt

**Environment**

Websote

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Note**
Any bug report which modified by user will be closed without any futher discussion nor fixes

**Comment by dalisoft** [comment]
Thank you @ThomasRedstone 
I am happy to merge if there you can create PR. Thank you
